/**
 * Copyright 2015 NaverCorp. All rights Reserved.
 * Naver PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */
package com.nts.reservation.dao;

/**
* @author  : 이승수
*/
public class DetailProductSqls {
	public static final String GET_AVERAGE_SCORE = "SELECT AVG(score) "
		+ "FROM "
		+ "reservation_user_comment AS c "
		+ "INNER JOIN reservation_info AS ri "
		+ "ON ri.id = c.reservation_info_id "
		+ "WHERE ri.display_info_id = :displayInfoId";

	public static final String GET_COMMENTS = "SELECT "
		+ "c.comment"
		+ ", c.id AS comment_id"
		+ ", c.create_date"
		+ ", c.modify_date"
		+ ", c.product_id"
		+ ", ri.reservation_date"
		+ ", ri.reservation_email"
		+ ", c.reservation_info_id"
		+ ", ri.reservation_name"
		+ ", ri.reservation_tel AS reservation_telephone"
		+ ", c.score "
		+ "FROM "
		+ "reservation_user_comment AS c "
		+ "INNER JOIN reservation_info AS ri "
		+ "ON ri.id = c.reservation_info_id "
		+ "WHERE ri.display_info_id = :displayInfoId ";
	public static final String GET_COMMENT_IMAGES = "SELECT f.content_type"
		+ ", c.create_date"
		+ ", f.delete_flag"
		+ ", ci.file_id"
		+ ", f.file_name"
		+ ", ci.id AS image_id"
		+ ", c.modify_date"
		+ ", c.reservation_info_id"
		+ ", c.id AS reservation_user_comment_id"
		+ ", f.save_file_name "
		+ "FROM reservation_user_comment AS c "
		+ "INNER JOIN reservation_user_comment_image as ci "
		+ "ON c.id = ci.reservation_user_comment_id "
		+ "INNER JOIN file_info AS f "
		+ "ON ci.file_id = f.id "
		+ "WHERE reservation_user_comment_id = :commentId";

	public static final String GET_DISPLAY_INFO = "SELECT "
		+ "c.id AS category_id"
		+ ", c.name AS category_name"
		+ ", d.create_date"
		+ ", d.id AS display_info_id"
		+ ", d.email"
		+ ", d.homepage"
		+ ", d.modify_date"
		+ ", d.opening_hours"
		+ ", d.place_lot"
		+ ", d.place_name"
		+ ", d.place_street"
		+ ", p.content AS product_content"
		+ ", p.description AS product_description"
		+ ", p.event AS product_event"
		+ ", p.id AS product_id"
		+ ", d.tel AS telephone "
		+ "FROM "
		+ "display_info as d "
		+ "INNER JOIN product AS p "
		+ "ON d.product_id = p.id "
		+ "INNER JOIN category AS c "
		+ "ON p.category_id = c.id "
		+ "WHERE d.id = :displayInfoId ";
	public static final String GET_DISPLAY_INFO_IMAGE = "SELECT "
		+ "f.content_type"
		+ ", d.create_date"
		+ ", f.delete_flag"
		+ ", di.display_info_id"
		+ ", di.id AS display_info_image_id"
		+ ", di.file_id"
		+ ", d.modify_date"
		+ ", f.save_file_name "
		+ "FROM "
		+ "display_info_image AS di "
		+ "INNER JOIN display_info AS d "
		+ "ON di.display_info_id = d.id "
		+ "INNER JOIN file_info AS f "
		+ "ON di.file_id = f.id "
		+ "WHERE d.id = :displayInfoId ";

	public static final String GET_PRODUCT_IMAGES = "SELECT "
		+ "f.content_type"
		+ ", f.create_date"
		+ ", f.delete_flag"
		+ ", pi.file_id AS file_info_id"
		+ ", f.file_name"
		+ ", f.modify_date"
		+ ", pi.product_id"
		+ ", pi.id AS product_image_id"
		+ ", f.save_file_name"
		+ ", pi.type "
		+ "FROM "
		+ "product_image AS pi "
		+ "INNER JOIN file_info AS f "
		+ "ON pi.file_id = f.id "
		+ "INNER JOIN display_info AS d "
		+ "ON pi.product_id = d.product_id "
		+ "WHERE pi.type = 'ma'"
		+ "AND d.id = :displayInfoId ";
	public static final String GET_PRODUCT_PRICES = "SELECT "
		+ "pp.create_date"
		+ ", pp.discount_rate"
		+ ", pp.modify_date"
		+ ", pp.price"
		+ ", pp.price_type_name"
		+ ", pp.product_id"
		+ ", pp.id AS product_price_id "
		+ "FROM "
		+ "product_price AS pp "
		+ "INNER JOIN display_info as d "
		+ "ON pp.product_id = d.product_id "
		+ "WHERE d.id = :displayInfoId ";
}
