"use strict";
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
var react_1 = __importStar(require("react"));
var DetailPage = /** @class */ (function (_super) {
    __extends(DetailPage, _super);
    function DetailPage() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    DetailPage.prototype.componentWillMount = function () {
    };
    DetailPage.prototype.render = function () {
        console.log(this.props.match.params.id);
        return (react_1.default.createElement("div", null,
            react_1.default.createElement("div", { id: "container" },
                react_1.default.createElement("div", { className: "header fade" },
                    react_1.default.createElement("header", { className: "header_tit" },
                        react_1.default.createElement("h1", { className: "logo" },
                            react_1.default.createElement("a", { href: "/reservation/", className: "lnk_logo", title: "\uB124\uC774\uBC84" },
                                " ",
                                react_1.default.createElement("span", { className: "spr_bi ico_n_logo" }, "\uB124\uC774\uBC84")),
                            " ",
                            react_1.default.createElement("a", { href: "/reservation/", className: "lnk_logo", title: "\uC608\uC57D" },
                                " ",
                                react_1.default.createElement("span", { className: "spr_bi ico_bk_logo" }, "\uC608\uC57D"))),
                        react_1.default.createElement("a", { href: "/reservation/bookinglogin", className: "btn_my" },
                            " ",
                            react_1.default.createElement("span", { title: "\uC608\uC57D\uD655\uC778" })))),
                react_1.default.createElement("div", { className: "ct main" },
                    react_1.default.createElement("div", null,
                        react_1.default.createElement("div", { className: "section_visual" },
                            react_1.default.createElement("header", null,
                                react_1.default.createElement("h1", { className: "logo" },
                                    react_1.default.createElement("a", { href: "/reservation/", className: "lnk_logo", title: "\uB124\uC774\uBC84" },
                                        " ",
                                        react_1.default.createElement("span", { className: "spr_bi ico_n_logo" }, "\uB124\uC774\uBC84")),
                                    react_1.default.createElement("a", { href: "/reservation/", className: "lnk_logo", title: "\uC608\uC57D" },
                                        " ",
                                        react_1.default.createElement("span", { className: "spr_bi ico_bk_logo" }, "\uC608\uC57D"))),
                                react_1.default.createElement("a", { href: "/reservation/myreservation", className: "btn_my" },
                                    " ",
                                    react_1.default.createElement("span", { className: "viewReservation", title: "\uC608\uC57D\uD655\uC778" }, "\uC608\uC57D\uD655\uC778"))),
                            react_1.default.createElement("div", { className: "pagination" },
                                react_1.default.createElement("div", { className: "bg_pagination" }),
                                react_1.default.createElement("div", { className: "figure_pagination" },
                                    react_1.default.createElement("span", { className: "num" }, "1"),
                                    " ",
                                    react_1.default.createElement("span", { className: "num off" },
                                        "/ ",
                                        react_1.default.createElement("span", null)))),
                            react_1.default.createElement("div", { className: "group_visual" },
                                react_1.default.createElement("div", null,
                                    react_1.default.createElement("div", { className: "container_visual", style: { width: "414px" } },
                                        react_1.default.createElement("ul", { className: "visual_img detail_swipe" })),
                                    react_1.default.createElement("div", { className: "prev" },
                                        react_1.default.createElement("div", { className: "prev_inn" },
                                            react_1.default.createElement("a", { href: "#", className: "btn_prev", title: "\uC774\uC804" },
                                                react_1.default.createElement("i", { className: "spr_book2 ico_arr6_lt off" })))),
                                    react_1.default.createElement("div", { className: "nxt" },
                                        react_1.default.createElement("div", { className: "nxt_inn" },
                                            react_1.default.createElement("a", { href: "#", className: "btn_nxt", title: "\uB2E4\uC74C" },
                                                " ",
                                                react_1.default.createElement("i", { className: "spr_book2 ico_arr6_rt" })))))),
                            react_1.default.createElement("div", { className: "group_btn_goto", style: { display: "none" } },
                                react_1.default.createElement("a", { className: "btn_goto_home", title: "\uD648\uD398\uC774\uC9C0", href: "#", target: "siteUrl" },
                                    react_1.default.createElement("i", { className: "fn fn-home1" })),
                                react_1.default.createElement("a", { className: "btn_goto_tel", title: "\uC804\uD654", href: "#" },
                                    " ",
                                    react_1.default.createElement("i", { className: "fn fn-call1" })),
                                react_1.default.createElement("a", { className: "btn_goto_mail", title: "\uC774\uBA54\uC77C", href: "#" },
                                    " ",
                                    react_1.default.createElement("i", { className: "fn fn-mail1" })),
                                react_1.default.createElement("a", { href: "#", className: "btn_goto_path", title: "\uAE38\uCC3E\uAE30" },
                                    " ",
                                    react_1.default.createElement("i", { className: "fn fn-path-find1" })),
                                react_1.default.createElement("a", { href: "#", className: "fn fn-share1 naver-splugin btn_goto_share", title: "\uACF5\uC720\uD558\uAE30" }))),
                        react_1.default.createElement("div", { className: "section_store_details" },
                            react_1.default.createElement("div", { className: "store_details close3" },
                                react_1.default.createElement("p", { className: "dsc" })),
                            react_1.default.createElement("a", { className: "bk_more _open" },
                                react_1.default.createElement("span", { className: "bk_more_txt" }, "\uD3BC\uCCD0\uBCF4\uAE30"),
                                react_1.default.createElement("i", { className: "fn fn-down2" })),
                            react_1.default.createElement("a", { className: "bk_more _close", style: { display: "none" } },
                                react_1.default.createElement("span", { className: "bk_more_txt" }, "\uC811\uAE30"),
                                react_1.default.createElement("i", { className: "fn fn-up2" }))),
                        react_1.default.createElement("div", { className: "section_event" },
                            react_1.default.createElement("div", { className: "event_info_box" },
                                react_1.default.createElement("div", { className: "event_info_tit" },
                                    react_1.default.createElement("h4", { className: "in_tit" },
                                        react_1.default.createElement("i", { className: "spr_book ico_evt" }),
                                        " ",
                                        react_1.default.createElement("span", null, "\uC774\uBCA4\uD2B8 \uC815\uBCF4"))),
                                react_1.default.createElement("div", { className: "event_info" },
                                    react_1.default.createElement("div", { className: "in_dsc" })))),
                        react_1.default.createElement("div", { className: "section_btn" },
                            react_1.default.createElement("button", { type: "button", className: "bk_btn" },
                                react_1.default.createElement("i", { className: "fn fn-nbooking-calender2" }),
                                " ",
                                react_1.default.createElement("span", null, "\uC608\uB9E4\uD558\uAE30"))),
                        react_1.default.createElement("div", { className: "section_review_list" },
                            react_1.default.createElement("div", { className: "review_box" },
                                react_1.default.createElement("h3", { className: "title_h3" }, "\uC608\uB9E4\uC790 \uD55C\uC904\uD3C9"),
                                react_1.default.createElement("div", { className: "short_review_area" },
                                    react_1.default.createElement("div", { className: "grade_area" },
                                        react_1.default.createElement("span", { className: "graph_mask" },
                                            " ",
                                            react_1.default.createElement("em", { className: "graph_value", style: { width: "0%" } })),
                                        " ",
                                        react_1.default.createElement("strong", { className: "text_value" },
                                            " ",
                                            react_1.default.createElement("span", null),
                                            " ",
                                            react_1.default.createElement("em", { className: "total" }, "5.0")),
                                        " ",
                                        react_1.default.createElement("span", { className: "join_count" },
                                            react_1.default.createElement("em", { className: "green" }, "\uAC74"),
                                            " \uB4F1\uB85D")),
                                    react_1.default.createElement("ul", { className: "list_short_review" })),
                                react_1.default.createElement("p", { className: "guide" },
                                    react_1.default.createElement("i", { className: "spr_book2 ico_bell" }),
                                    " ",
                                    react_1.default.createElement("span", null, "\uB124\uC774\uBC84 \uC608\uC57D\uC744 \uD1B5\uD574 \uC2E4\uC81C \uBC29\uBB38\uD55C \uC774\uC6A9\uC790\uAC00 \uB0A8\uAE34 \uD3C9\uAC00\uC785\uB2C8\uB2E4."))),
                            react_1.default.createElement("a", { className: "btn_review_more", href: "/reservation/review" },
                                " ",
                                react_1.default.createElement("span", null, "\uC608\uB9E4\uC790 \uD55C\uC904\uD3C9 \uB354\uBCF4\uAE30"),
                                " ",
                                react_1.default.createElement("i", { className: "fn fn-forward1" }))),
                        react_1.default.createElement("div", { className: "section_info_tab" },
                            react_1.default.createElement("ul", { className: "info_tab_lst" },
                                react_1.default.createElement("li", { className: "item active _detail" },
                                    react_1.default.createElement("a", { className: "anchor active" },
                                        react_1.default.createElement("span", null, "\uC0C1\uC138\uC815\uBCF4"))),
                                react_1.default.createElement("li", { className: "item _path" },
                                    react_1.default.createElement("a", { className: "anchor" },
                                        " ",
                                        react_1.default.createElement("span", null, "\uC624\uC2DC\uB294\uAE38")))),
                            react_1.default.createElement("div", { className: "detail_area_wrap" },
                                react_1.default.createElement("div", { className: "detail_area" },
                                    react_1.default.createElement("div", { className: "detail_info" },
                                        react_1.default.createElement("h3", { className: "blind" }, "\uC0C1\uC138\uC815\uBCF4"),
                                        react_1.default.createElement("ul", { className: "detail_info_group" },
                                            react_1.default.createElement("li", { className: "detail_info_lst" },
                                                react_1.default.createElement("strong", { className: "in_tit" }, "[\uC18C\uAC1C]"),
                                                react_1.default.createElement("p", { className: "in_dsc" })),
                                            react_1.default.createElement("li", { className: "detail_info_lst" },
                                                react_1.default.createElement("strong", { className: "in_tit" }, "[\uACF5\uC9C0\uC0AC\uD56D]"),
                                                react_1.default.createElement("ul", { className: "in_img_group" },
                                                    react_1.default.createElement("li", { className: "in_img_lst" },
                                                        react_1.default.createElement("img", { alt: "", className: "img_thumb", src: "https://ssl.phinf.net/naverbooking/20170131_238/14858250829398Pnx6_JPEG/%B0%F8%C1%F6%BB%E7%C7%D7.jpg?type=a1000" })))))))),
                            react_1.default.createElement("div", { className: "detail_location hide" },
                                react_1.default.createElement("div", { className: "box_store_info no_topline" },
                                    react_1.default.createElement("a", { href: "#", className: "store_location", title: "\uC9C0\uB3C4\uC6F9\uC73C\uB85C \uC5F0\uACB0" },
                                        " ",
                                        react_1.default.createElement("img", { className: "store_map img_thumb", alt: "map", src: "https://simg.pstatic.net/static.map/image?version=1.1&crs=EPSG:4326&baselayer=bl_vc_bg&exception=xml&scale=2&caller=mw_smart_booking&overlayers=ol_vc_an&center=127.0011948,37.5717079&markers=type,default2,127.0011948,37.5717079&level=11&w=340&h=150" }),
                                        react_1.default.createElement("span", { className: "img_border" }),
                                        " ",
                                        react_1.default.createElement("span", { className: "btn_map" },
                                            react_1.default.createElement("i", { className: "spr_book2 ico_mapview" }))),
                                    react_1.default.createElement("h3", { className: "store_name" }, "\uC5D4\uC5D0\uC774\uCE58\uC5D4\uD2F0\uCF13\uB9C1\uD06C(\uC8FC)"),
                                    react_1.default.createElement("div", { className: "store_info" },
                                        react_1.default.createElement("div", { className: "store_addr_wrap" },
                                            react_1.default.createElement("span", { className: "fn fn-pin2" }),
                                            react_1.default.createElement("p", { className: "store_addr store_addr_bold" }),
                                            react_1.default.createElement("p", { className: "store_addr" },
                                                react_1.default.createElement("span", { className: "addr_old" }, "\uC9C0\uBC88"),
                                                " ",
                                                react_1.default.createElement("span", { className: "addr_old_detail" })),
                                            react_1.default.createElement("p", { className: "store_addr addr_detail" }, "\uB450\uC0B0\uC544\uD2B8\uC13C\uD130 \uC5F0\uAC15\uD640")),
                                        react_1.default.createElement("div", { className: "lst_store_info_wrap" },
                                            react_1.default.createElement("ul", { className: "lst_store_info" },
                                                react_1.default.createElement("li", { className: "item" },
                                                    react_1.default.createElement("span", { className: "item_lt" },
                                                        " ",
                                                        react_1.default.createElement("i", { className: "fn fn-call2" }),
                                                        " ",
                                                        react_1.default.createElement("span", { className: "sr_only" }, "\uC804\uD654\uBC88\uD638")),
                                                    " ",
                                                    react_1.default.createElement("span", { className: "item_rt" },
                                                        " ",
                                                        react_1.default.createElement("a", { href: "tel:02-548-0597", className: "store_tel" }, "02-548-0597")))))),
                                    react_1.default.createElement("div", { className: "bottom_common_path column2" },
                                        react_1.default.createElement("a", { href: "#", className: "btn_path" },
                                            " ",
                                            react_1.default.createElement("i", { className: "fn fn-path-find2" }),
                                            react_1.default.createElement("span", null, "\uAE38\uCC3E\uAE30")),
                                        " ",
                                        react_1.default.createElement("a", { href: "#", className: "btn_navigation before" },
                                            " ",
                                            react_1.default.createElement("i", { className: "fn fn-navigation2" }),
                                            " ",
                                            react_1.default.createElement("span", null, "\uB0B4\uBE44\uAC8C\uC774\uC158"))))))))),
            react_1.default.createElement("footer", null,
                react_1.default.createElement("div", { className: "gototop" },
                    react_1.default.createElement("a", { href: "#", className: "lnk_top" },
                        " ",
                        react_1.default.createElement("span", { className: "lnk_top_text" }, "TOP"))),
                react_1.default.createElement("div", { className: "footer" },
                    react_1.default.createElement("p", { className: "dsc_footer" }, "\uB124\uC774\uBC84(\uC8FC)\uB294 \uD1B5\uC2E0\uD310\uB9E4\uC758 \uB2F9\uC0AC\uC790\uAC00 \uC544\uB2C8\uBA70, \uC0C1\uD488\uC758\uC815\uBCF4, \uAC70\uB798\uC870\uAC74, \uC774\uC6A9 \uBC0F \uD658\uBD88 \uB4F1\uACFC \uAD00\uB828\uD55C \uC758\uBB34\uC640 \uCC45\uC784\uC740 \uAC01 \uD68C\uC6D0\uC5D0\uAC8C \uC788\uC2B5\uB2C8\uB2E4."),
                    react_1.default.createElement("span", { className: "copyright" }, "\u00A9 NAVER Corp.")))));
    };
    return DetailPage;
}(react_1.Component));
exports.default = DetailPage;
